
spring:
  datasource:
    name: test
    url: jdbc:mysql://106.12.55.131:3306/springboot_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 2
    host: 106.12.55.131
    port: 6379
    password: root
  cache:
    type: redis
# rabbitmq配置参数
  rabbitmq:
    host: 106.12.55.131
    port: 5672
    username: lxh
    password: lxh
    virtual-host: /demo
    listener:
      simple:
        # 采用手动应答
        acknowledge-mode: manual
        # 当前监听容器数
        concurrency: 1
        # 最大数
        max-concurrency: 1
        # 是否支持重试
        retry:
          enabled: true
    # 支持发布确认
    publisher-confirms: true
    # 支持发布返回
    publisher-returns: true

#队列配置信息(delayed为延时队列)
#创建延时队列时 必须要在服务器端 安装延时队列插件 参考：https://www.jianshu.com/p/8fe6947efa53
rabbitmq:
  delayed-queue-name: delayed-queue-dev
  delayed-exchange-name: delay-exchange-dev
  msg-send-exchange: msg-send-exchange-dev
  msg-send-queue: msg-send-queue-dev




