
spring:
  datasource:
    name: test
    url: jdbc:mysql://bj-cdb-bzs3kghm.sql.tencentcdb.com:63339/db_nsop_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 2
    host:
    port: 6379
    password:
  cache:
    type: redis


